#Wine Dataset
In this exercise, Train the MultiLayer Perceptron Algorithm for Wine Dataset.

In [1]:
#Cesar Borroto
#SID 6041526
import pandas as pd
import numpy as np
import matplotlib as plt
# Download the dataset from https://archive.ics.uci.edu/ml/datasets/wine
# Load the wine dataset

In [2]:
wine = pd.read_csv('wine.data', names = ["Cultivator", "Alcohol", "Malic_acid", "Ash", "Alcalinity_of_ash", "Magnesium", "Total_phenols", "Flavanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])

In [3]:
# Print the top 5 rows
wine.head()

Cultivator  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0           1    14.23        1.71  2.43               15.6        127   
1           1    13.20        1.78  2.14               11.2        100   
2           1    13.16        2.36  2.67               18.6        101   
3           1    14.37        1.95  2.50               16.8        113   
4           1    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [4]:
# Check the statistical values of each features
wine.describe()

Cultivator     Alcohol  Malic_acid         Ash  Alcalinity_of_ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000   
mean     1.938202   13.000618    2.336348    2.366517          19.494944   
std      0.775035    0.811827    1.117146    0.274344           3.339564   
min      1.000000   11.030000    0.740000    1.360000          10.600000   
25%      1.000000   12.362500    1.602500    2.210000          17.200000   
50%      2.000000   13.050000    1.865000    2.360000          19.500000   
75%      3.000000   13.677500    3.082500    2.557500          21.500000   
max      3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total_phenols  Flavanoids  Nonflavanoid_phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color_intensity         Hue       OD280      Proline  
count       178.000000       178.000000  178.000000  178.000000   178.000000  
mean          1.590899         5.058090    0.957449    2.611685   746.893258  
std           0.572359         2.318286    0.228572    0.709990   314.907474  
min           0.410000         1.280000    0.480000    1.270000   278.000000  
25%           1.250000         3.220000    0.782500    1.937500   500.500000  
50%           1.555000         4.690000    0.965000    2.780000   673.500000  
75%           1.950000         6.200000    1.120000    3.170000   985.000000  
max           3.580000        13.000000    1.710000    4.000000  1680.000000

In [5]:
# Print the shape of data 
wine.shape

(178, 14)

In [6]:
# Divide data into features and target column as X and y respectively
X = wine.drop("Cultivator",axis=1)
y = wine["Cultivator"]

In [7]:
X.head()
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Cultivator, Length: 178, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [9]:
# Split the data into train and test
X_train.shape

(133, 13)

In [10]:
# Scale the data using standardScaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [11]:
scaler.fit(X_train)

StandardScaler()

In [12]:
X_train=scaler.transform(X_train)

In [13]:
X_train

array([[-0.12368378,  0.37636222,  1.18142196, ..., -0.76859165,
        -0.36062634, -0.49435528],
       [ 0.81069267,  0.77496917,  0.60053797, ...,  0.06156355,
        -1.03967918, -0.2440369 ],
       [-1.73425372, -0.34998823, -0.34339853, ...,  0.93541113,
         0.54015803, -1.29224513],
       ...,
       [ 0.51562642,  1.16471819,  0.81836946, ..., -0.41905262,
        -1.39999292, -0.1971022 ],
       [-0.0868005 ,  0.94326989, -0.08926178, ..., -1.16182306,
        -1.13668672, -0.2596818 ],
       [-1.80802029, -0.29684063,  3.1056002 , ..., -0.06951359,
         1.55180817, -0.91676756]])

In [14]:
X_test=scaler.transform(X_test)

In [15]:
X_test

array([[-9.10527114e-01,  3.94078085e-01, -5.61230026e-01,
        -5.00025881e-01, -8.36072572e-01,  2.68572535e-01,
         2.22192907e-01, -9.38775747e-01,  6.38165553e-01,
        -1.30798870e+00,  8.91718748e-01,  1.01133755e+00,
        -1.46433902e+00],
       [ 2.08265745e-01, -5.36004805e-01, -8.51672024e-01,
        -2.57539718e+00,  5.80239640e-03,  5.85380935e-01,
         7.19597028e-01, -8.56848467e-01, -5.59171486e-01,
        -3.54546973e-01,  4.54794958e-01,  1.14991976e+00,
         9.13685630e-01],
       [-9.59704822e-01, -5.80294466e-01, -9.24282523e-01,
        -1.94824219e-01, -1.39732255e+00, -9.98661066e-01,
         7.62642320e-03,  4.43516101e-02,  3.10650825e-02,
        -7.73548268e-01,  2.36333063e-01,  8.31180676e-01,
        -7.75963466e-01],
       [-1.23683785e-01,  1.25329752e+00,  9.99895713e-01,
        -3.16904884e-01,  1.46114891e-01,  2.05210855e-01,
         3.78241258e-01, -9.38775747e-01,  6.21301651e-01,
        -3.03240692e-01,  3.67410200e

In [16]:
from sklearn.neural_network import MLPClassifier

In [17]:
mlp=MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [18]:
mlp.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(13, 13, 13), max_iter=500)

In [19]:
# Develop a MLP architecture as described in class and train the model.
predictions=mlp.predict(X_test)

In [20]:
# Perform the predictions and generate the classification report and confusion matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))


[[15  1  0]
 [ 0 19  1]
 [ 0  1  8]]


In [21]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       0.90      0.95      0.93        20
           3       0.89      0.89      0.89         9

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45

